/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 squid.gltf --transform
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/handsome-squidward-652761a0a5b146a39c71f83b68411e39
Title: Handsome Squidward
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Squid(props) {
  const { nodes, materials } = useGLTF("/squid-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Material.003"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/squid-transformed.glb");
