/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 vk.gltf --transform
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vk-logo-5b869851f79b45e6895f4081e76620bf
Title: VK Logo
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VkLogo(props) {
  const { nodes, materials } = useGLTF("/vk-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blank} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.logo} />
      </group>
    </group>
  );
}

useGLTF.preload("/vk-transformed.glb");
